#include "stdafx.h"
#include "net.minecraft.world.level.h"
#include "net.minecraft.world.level.tile.h"
#include "HolidayTreeFeature.h"

HolidayTreeFeature::HolidayTreeFeature(int blockId) : Feature(blockId)
{
}

bool HolidayTreeFeature::place(Level *level, Random *random, int x, int y, int z)
{
    if (level->getTile(x, y - 1, z) == Tile::aetherGrass_Id)
	{
		int data = (random->nextInt(4) == 0) ? 5 : 4;
		
    	for (int y1 = 0; y1 <= 8; y1++)
        placeBlock(level, x, y + y1, z, Tile::skyrootLog_Id, 0); 
      	placeBlock(level, x, y + 9, z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 2, 2 + z, Tile::skyrootLog_Id, 0);
      	placeBlock(level, x + 0, y + 2, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 2, 4 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 2, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 2, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 2, -4 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 2, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 2, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 4, y + 2, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 2, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 2, 0 + z, Tile::skyrootLog_Id, 0);
      	placeBlock(level, x + -4, y + 2, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, 4 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, 2 + z, Tile::skyrootLog_Id, 0);
      	placeBlock(level, x + -1, y + 2, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, 4 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, -4 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, -2 + z, Tile::skyrootLog_Id, 0);
     	placeBlock(level, x + -1, y + 2, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, -4 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 4, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 4, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -4, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -4, y + 2, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 2, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 2, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 2, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 2, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 2, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 2, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 2, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 2, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 2, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 2, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 3, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 3, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 3, 4 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 3, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 3, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 3, -4 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 3, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 3, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 4, y + 3, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 3, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 3, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -4, y + 3, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 3, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 3, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 3, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 3, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 3, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 3, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 3, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 3, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 3, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 3, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 3, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 3, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 3, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 4, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 4, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 4, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 4, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 4, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 4, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 4, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 4, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 4, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 4, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 4, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 4, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 4, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 4, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 5, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 5, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 5, 3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 5, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 5, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 5, -3 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 5, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 5, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 3, y + 5, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 5, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 5, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -3, y + 5, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 5, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 5, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 5, 1 + z, Tile::skyrootLog_Id, 0);
      	placeBlock(level, x + -1, y + 5, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 5, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 5, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 5, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 5, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 5, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 5, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 5, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 5, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 5, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 5, 1 + z, Tile::skyrootLog_Id, 0);
      	placeBlock(level, x + -1, y + 5, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 5, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 5, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 5, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 5, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 5, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 6, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 6, 2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 6, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 6, -2 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 6, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 2, y + 6, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 6, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -2, y + 6, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 6, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 6, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 6, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 6, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 6, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 6, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 6, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 6, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 7, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 7, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 7, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 7, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 7, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 7, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 7, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 7, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 7, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 7, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 7, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 7, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 8, 1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 0, y + 8, -1 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + 1, y + 8, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x + -1, y + 8, 0 + z, Tile::netherLeaves_Id, data);
      	placeBlock(level, x, y - 1, z, Tile::aetherDirt_Id, 0);
		
		return true;
    } 
    return false;
}
